version: '3.8'

services:
    api:
        env_file:
            - .env
        # image: windsoft2018/ogo_api:dev
        restart: always
        ports:
            - ${PORT}:${PORT}
        build:
            context: .
        volumes:
            - ./uploads:/app/uploads
        networks:
            - overlay
networks:
    overlay:
